<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_TOR_MS" Id="{5487bb2d-2e0b-4636-a596-305325a2a6fb}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TOR_MS EXTENDS FB_TOR_Base
//////////////////
//  Door sensor system . State = True >> Door Closed .
//////////////////

VAR_INPUT PERSISTENT
	// Parameters of the Object (instance/model specific) 
		ParamTempoDoorAlarm			: TIME := T#10S ;	// (S) Tempo for Door sensor alarm 
		
END_VAR

VAR_OUTPUT
	//Child objects
	
END_VAR

VAR_INPUT
	// I/O Inputs 		                                     				
		
END_VAR

VAR
	//M_ALARMMANAGEMENT VARIABLES//
		TP_Fermeture			: TP;				//(NA) Tempo to detect door opened for too long time . 
		RS_fermeture			: RS;
		
		MesDataExd			: TOR_Standard ;  
		


END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Execute" Id="{544f5867-7d79-4716-ab42-e112e3d84792}">
      <Declaration><![CDATA[METHOD M_Execute
//////////////////
//  Method Calls 
/////////////////

VAR 
	// Method local variables (reinitialized at each cycle) 
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
SUPER^.M_Execute() ; 
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TOR_MS">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_TOR_MS.M_Execute">
      <LineId Id="55" Count="0" />
      <LineId Id="2" Count="0" />
      <LineId Id="65" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>