<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_TOR_Standard" Id="{d507d0ce-ff85-44ce-be0c-35e924c62038}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TOR_Standard EXTENDS FB_TOR_Base
//////////////////
//  Circuit Breaker
//////////////////

VAR_INPUT PERSISTENT
	// Parameters of the Object (instance/model specific) 
		
		
END_VAR

VAR_OUTPUT
	//Child objects
	
END_VAR

VAR_INPUT
	// I/O Inputs 		                                     				
		
END_VAR

VAR
	//M_ALARMMANAGEMENT VARIABLES//
		
MesDataExd			: TOR_Standard ;  

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TOR_Standard">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>