<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_TOR_CB" Id="{458e1c02-4479-4190-985f-d7ff6eca70f8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TOR_CB EXTENDS FB_TOR_Base
//////////////////
//  Door sensor system . State = True >> Door Closed .
//////////////////

VAR_INPUT PERSISTENT
	// Parameters of the Object (instance/model specific) 
		
		
END_VAR

VAR_OUTPUT
	//Child objects
	
END_VAR

VAR_INPUT
	// I/O Inputs 		                                     				
		
END_VAR

VAR
	//M_ALARMMANAGEMENT VARIABLES//
		
MesDataExd			: TOR_Standard ;  

	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TOR_CB">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>