<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_UPS_Eneris" Id="{d46c7c6d-f251-4407-9748-964b2ea6e8f6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_UPS_ENERIS EXTENDS FB_UPS_Base
//////////////////
// UPS 
//////////////////
VAR_INPUT PERSISTENT
	// Parameters of the Object (instance/model specific) 
	
END_VAR

VAR_OUTPUT
	//Child objects
	
END_VAR

VAR_INPUT
	// I/O Inputs
		IN_MesCbUPS_IO					: BOOL ; // 1 = opened. 
END_VAR

VAR
	//M_ALARMMANAGEMENT VARIABLES//
		
	//M_READ//

	MesDataExd				: UPS_ENERIS ; 
	
		
	//M_EXECUTE //
		
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Execute" Id="{7718f825-f889-4c23-b487-7cbd2ed49a56}">
      <Declaration><![CDATA[METHOD M_Execute
//////////////////
//  Method Calls 
/////////////////

VAR 
	// Method local variables (reinitialized at each cycle) 

END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_UPS_Eneris">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_UPS_Eneris.M_Execute">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>