<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_WordsToDint64BE" Id="{bb645748-e94b-47a2-906c-f9f19dab7d27}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_WordsToDint64BE
////////////////// 
// Merge four words into a DINT or UDINT with big endian coding. And finally Output a Real. 
//////////////////	
VAR_OUTPUT
	OutCalDint : ULINT ; 	
END_VAR

VAR_INPUT
	InFirstWord 		: WORD; 
	InSecondWord 		: WORD; 
	InThirdWord 		: WORD; 
	InFourthWord 		: WORD; 
END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[OutCalDint:= LWORD_TO_ULINT( (SHL(WORD_TO_LWORD(InFirstWord),48) OR SHL(WORD_TO_LWORD(InFirstWord),32)OR SHL(WORD_TO_LWORD(InThirdWord),16)OR WORD_TO_LWORD(InFourthWord)));
	]]></ST>
    </Implementation>
    <LineIds Name="FB_WordsToDint64BE">
      <LineId Id="139" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>