<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_Transfo_HVCom" Id="{a9bb1baf-4750-4717-8fd3-21b4c59b39a9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Transfo_HVCom EXTENDS FB_Transfo_Base
//////////////////
// High Voltage transformer with Transfo or DMCR detection . 
//////////////////

VAR_INPUT PERSISTENT
	// Parameters of the Object (instance/model specific) 
	
END_VAR

VAR_OUTPUT
	//Child objects
	
END_VAR

VAR_INPUT

END_VAR

VAR
MesDataExd					: Transfo_HV ; 
		
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Transfo_HVCom">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>