<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_Transfo_Base" Id="{cfe582a0-0c9f-4eac-9b4d-85c949d4eaf5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Transfo_Base
//////////////////
// High Voltage transformer with Transfo or DMCR detection . 
//////////////////

VAR_INPUT PERSISTENT
	// Parameters of the Object (instance/model specific) 

END_VAR

VAR_OUTPUT
	//Child objects
	
END_VAR

VAR_INPUT
		// Transfo

END_VAR

VAR
	//MesDataExd					: Transfo ; 
		
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Execute" Id="{3e1fdba9-7259-4a22-9e0e-06ea571a5c31}">
      <Declaration><![CDATA[METHOD M_Execute
//////////////////
//  Method Calls 
/////////////////

VAR 
	// Method local variables (reinitialized at each cycle) 

END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Transfo_Base">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_Transfo_Base.M_Execute">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>